# Generated by Django 2.2.1 on 2019-06-07 14:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('idep', '0004_remove_idepanosfinaisindiceescolas_cod_mec'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='idepanosfinaismetasescolas',
            name='cod_mec',
        ),
    ]
