from django.contrib.auth.base_user import AbstractBaseUser
from django.contrib.auth.models import PermissionsMixin, UserManager
from django.db import models


# Create your models here.
class Servidores(models.Model):
    rf = models.IntegerField(blank=True, null=True)
    cd_cpf_pessoa = models.TextField(blank=True, null=True)
    nm_pessoa = models.TextField(blank=True, null=True)
    cd_serv_sme = models.IntegerField(blank=True, null=True)
    mes_nasc = models.IntegerField(blank=True, null=True)
    ano_nasc = models.IntegerField(blank=True, null=True)
    idade = models.IntegerField(blank=True, null=True)
    cd_sexo = models.TextField(blank=True, null=True)
    cd_municipio_nasc = models.IntegerField(blank=True, null=True)
    dc_municipio_nasc = models.TextField(blank=True, null=True)
    uf_municipio_nasc = models.TextField(blank=True, null=True)
    cd_pais_nasc = models.IntegerField(blank=True, null=True)
    dc_pais_nasc = models.TextField(blank=True, null=True)
    cd_municipio_res = models.IntegerField(blank=True, null=True)
    dc_municipio_res = models.TextField(blank=True, null=True)
    uf_municipio_res = models.TextField(blank=True, null=True)
    cd_raca_cor = models.IntegerField(blank=True, null=True)
    dc_raca_cor = models.TextField(blank=True, null=True)
    cd_def = models.IntegerField(blank=True, null=True)
    dc_def = models.TextField(blank=True, null=True)
    nivel_form = models.TextField(blank=True, null=True)
    dc_sit_func = models.TextField(blank=True, null=True)
    cd_cargo_base = models.IntegerField(blank=True, null=True)
    dc_cargo_base = models.TextField(blank=True, null=True)
    cd_area_atuacao_base = models.IntegerField(blank=True, null=True)
    dc_area_atuacao_base = models.TextField(blank=True, null=True)
    dt_inicio_cargo_base = models.TextField(blank=True, null=True)
    cd_unidade_base = models.TextField(blank=True, null=True)
    tp_unidade_base = models.TextField(blank=True, null=True)
    dc_unidade_base = models.TextField(blank=True, null=True)
    sigla_lotacao = models.TextField(blank=True, null=True)
    tp_lotacao = models.TextField(blank=True, null=True)
    cd_cargo_atual = models.IntegerField(blank=True, null=True)
    dc_cargo_atual = models.TextField(blank=True, null=True)
    cd_area_atuacao_cargo_atual = models.TextField(blank=True, null=True)
    dc_area_atuacao_cargo_atual = models.TextField(blank=True, null=True)
    cd_unidade_educacao_atual = models.TextField(blank=True, null=True)
    tp_unidade_educacao_atual = models.TextField(blank=True, null=True)
    dc_unidade_educacao_atual = models.TextField(blank=True, null=True)
    sigla_atual = models.TextField(blank=True, null=True)
    cd_unidade_funcao = models.IntegerField(blank=True, null=True)
    cd_funcao = models.IntegerField(blank=True, null=True)
    dc_funcao = models.TextField(blank=True, null=True)
    dt_inicio_funcao = models.TextField(blank=True, null=True)
    cd_unidade_sobreposto = models.TextField(blank=True, null=True)
    cd_sobreposto = models.IntegerField(blank=True, null=True)
    dc_sobreposto = models.TextField(blank=True, null=True)
    dt_inicio_sobreposto = models.TextField(blank=True, null=True)
    database = models.TextField(blank=True, null=True)


class ServidorUser(AbstractBaseUser, PermissionsMixin):
    REQUIRED_FIELDS = ('cd_cpf_pessoa', 'ano_nasc')
    USERNAME_FIELD = 'rf'
    rf = models.IntegerField(unique=True)
    password = models.TextField(blank=True, null=True)
    ano_nasc = models.IntegerField(blank=True, null=True)
    mes_nasc = models.IntegerField(blank=True, null=True)
    objects = UserManager()
