# Generated by Django 2.2.1 on 2019-05-28 19:33

import django.contrib.auth.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0011_update_proxy_permissions'),
    ]

    operations = [
        migrations.CreateModel(
            name='Servidores',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rf', models.IntegerField(blank=True, null=True)),
                ('cd_cpf_pessoa', models.TextField(blank=True, null=True)),
                ('nm_pessoa', models.TextField(blank=True, null=True)),
                ('cd_serv_sme', models.IntegerField(blank=True, null=True)),
                ('mes_nasc', models.IntegerField(blank=True, null=True)),
                ('ano_nasc', models.IntegerField(blank=True, null=True)),
                ('idade', models.IntegerField(blank=True, null=True)),
                ('cd_sexo', models.TextField(blank=True, null=True)),
                ('cd_municipio_nasc', models.IntegerField(blank=True, null=True)),
                ('dc_municipio_nasc', models.TextField(blank=True, null=True)),
                ('uf_municipio_nasc', models.TextField(blank=True, null=True)),
                ('cd_pais_nasc', models.IntegerField(blank=True, null=True)),
                ('dc_pais_nasc', models.TextField(blank=True, null=True)),
                ('cd_municipio_res', models.IntegerField(blank=True, null=True)),
                ('dc_municipio_res', models.TextField(blank=True, null=True)),
                ('uf_municipio_res', models.TextField(blank=True, null=True)),
                ('cd_raca_cor', models.IntegerField(blank=True, null=True)),
                ('dc_raca_cor', models.TextField(blank=True, null=True)),
                ('cd_def', models.IntegerField(blank=True, null=True)),
                ('dc_def', models.TextField(blank=True, null=True)),
                ('nivel_form', models.TextField(blank=True, null=True)),
                ('dc_sit_func', models.TextField(blank=True, null=True)),
                ('cd_cargo_base', models.IntegerField(blank=True, null=True)),
                ('dc_cargo_base', models.TextField(blank=True, null=True)),
                ('cd_area_atuacao_base', models.IntegerField(blank=True, null=True)),
                ('dc_area_atuacao_base', models.TextField(blank=True, null=True)),
                ('dt_inicio_cargo_base', models.TextField(blank=True, null=True)),
                ('cd_unidade_base', models.TextField(blank=True, null=True)),
                ('tp_unidade_base', models.TextField(blank=True, null=True)),
                ('dc_unidade_base', models.TextField(blank=True, null=True)),
                ('sigla_lotacao', models.TextField(blank=True, null=True)),
                ('tp_lotacao', models.TextField(blank=True, null=True)),
                ('cd_cargo_atual', models.IntegerField(blank=True, null=True)),
                ('dc_cargo_atual', models.TextField(blank=True, null=True)),
                ('cd_area_atuacao_cargo_atual', models.TextField(blank=True, null=True)),
                ('dc_area_atuacao_cargo_atual', models.TextField(blank=True, null=True)),
                ('cd_unidade_educacao_atual', models.TextField(blank=True, null=True)),
                ('tp_unidade_educacao_atual', models.TextField(blank=True, null=True)),
                ('dc_unidade_educacao_atual', models.TextField(blank=True, null=True)),
                ('sigla_atual', models.TextField(blank=True, null=True)),
                ('cd_unidade_funcao', models.IntegerField(blank=True, null=True)),
                ('cd_funcao', models.IntegerField(blank=True, null=True)),
                ('dc_funcao', models.TextField(blank=True, null=True)),
                ('dt_inicio_funcao', models.TextField(blank=True, null=True)),
                ('cd_unidade_sobreposto', models.TextField(blank=True, null=True)),
                ('cd_sobreposto', models.IntegerField(blank=True, null=True)),
                ('dc_sobreposto', models.TextField(blank=True, null=True)),
                ('dt_inicio_sobreposto', models.TextField(blank=True, null=True)),
                ('database', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='ServidorUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('rf', models.IntegerField(unique=True)),
                ('password', models.TextField(blank=True, null=True)),
                ('ano_nasc', models.IntegerField(blank=True, null=True)),
                ('mes_nasc', models.IntegerField(blank=True, null=True)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.Group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.Permission', verbose_name='user permissions')),
            ],
            options={
                'abstract': False,
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
    ]
